[plugin]
id = "icu.tatyrealms.nemos"
name = "网易云音乐"
version = "0.1.1"
author = "TATyKeFei"
description = "把网易云官方网页播放器嵌进 Steam 里，并实现一些Web版没有的功能"

[backend]
entry = "backend/main.lua"
sources = ["backend/**/*.lua"]

[assets]
resources = ["backend/mpris_helper.py"]

[frontend]
entry = "frontend/index.tsx"

[frontend.globals]

[compiler]
# output_path = "auto"
output_path = "dist/icu.tatyrealms.nemos.star"

[dev]
auto_restart = true
reload_steamui_when = "both"

[inspect]
depth = 4
colors = true
show_hidden = true

[logger]
padding = 0
backend_prefix = "BCK"
frontend_prefix = "FRT"

[patches]
debug = false
